name = "GlobtimPostProcessing"
uuid = "b470b6bb-4443-493e-998d-c7c5e1aa9116"
license = "GPL-3.0"
version = "0.1.0"
authors = ["Georgy Scholten <scholtengeorgy@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
CSV = "0.10"
JLD2 = "0.5, 0.6"
DataFrames = "1.6"
Dates = "1"
FiniteDiff = "2"
ForwardDiff = "0.10"
JSON = "0.21, 1"
JSON3 = "1.14"
LinearAlgebra = "1"
Optim = "1"
PrettyTables = "2"
Printf = "1"
ProgressMeter = "1.10"
REPL = "1"
Statistics = "1"
StatsBase = "0.34.7"
UnicodePlots = "3"
julia = "1.10, 1.11, 1.12"
