name = "GlobtimPostProcessing"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
license = "GPL-3.0"
authors = ["Georgy Scholten <scholtengeorgy@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tidier = "f0413319-3358-4bb0-8e7c-0c83523a93bd"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
CSV = "0.10"
CairoMakie = "0.11, 0.12"
DataFrames = "1.6"
Dates = "1"
GLMakie = "0.9, 0.10"
JSON = "0.21"
JSON3 = "1.14"
LinearAlgebra = "1"
Printf = "1"
ProgressMeter = "1.10"
Statistics = "1"
Tidier = "1.5.1"
VegaLite = "3.3.0"
julia = "1.10, 1.11"
