name = "GlobtimPostProcessing"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"  # TODO: Generate proper UUID
license = "GPL-3.0"
authors = ["Georgy Scholten <scholtengeorgy@gmail.com>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.11, 0.12"
CSV = "0.10"
DataFrames = "1.6"
Dates = "1"
GLMakie = "0.9, 0.10"
JSON = "0.21"
JSON3 = "1.14"
LinearAlgebra = "1"
Printf = "1"
Statistics = "1"
julia = "1.10, 1.11"
