name = "GlobtimPostProcessing"
uuid = "b470b6bb-4443-493e-998d-c7c5e1aa9116"
license = "GPL-3.0"
version = "0.1.0"
authors = ["Georgy Scholten <scholtengeorgy@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Globtim = "00da9514-6261-47e9-8848-33640cb1e528"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tidier = "f0413319-3358-4bb0-8e7c-0c83523a93bd"

[compat]
CSV = "0.10"
DataFrames = "1.6"
Dates = "1"
JSON = "0.21"
JSON3 = "1.14"
LinearAlgebra = "1"
PrettyTables = "2"
Printf = "1"
ProgressMeter = "1.10"
Statistics = "1"
StatsBase = "0.34.7"
Tidier = "0.7.7"
julia = "1.10, 1.11"
